### ISSUE TITLE
Extension could not be loaded in Chrome 19 (Dev) – fix included

### ISSUE THREAD

**Issue by fhemberger** [jonathanmayer/Do-Not-Track#4]
The extension could not be loaded neither from Chrome Web Store or local in Chrome 19 (Dev-Channel).

On local installation, I get the error message "Background page is not supported in this manifest version". Removing the line `"manifest_version": 2,` from manifest.json does the trick. The property "manifest_version" is also not documented in the [manifest format description](http://code.google.com/chrome/extensions/manifest.html).

**Comment by saizai** [comment]
In 19.0.1084.46, clicking 'add to chrome' results in a generic error asking to reload the page. Reloading of course doesn't make it go away.

**Comment by fhemberger** [comment]
@saizai This error seems not related with the extension, had this issue with other Chrome extensions, too.
